sudo: required
services:
  - docker
language: ruby
rvm:
  - "2.2"
  - "2.4.2"
  - "2.5"
  - ruby-head
env:
  - "PGVERSION=10.0-1-linux-x64 PATH=\"/opt/PostgreSQL/10/bin:$PATH\""
  - "PGVERSION=9.3.19-1-linux-x64 PATH=\"/opt/PostgreSQL/9.3/bin:$PATH\""
  - "PGCROSS=true"
matrix:
  include:
    - language: ruby
      rvm: "2.5"
      # i686 (32bit environment case)
      env:
        - DOCKER=i686
        # 32 bit edition.
        - PGVERSION=10.0-1-linux
        - PATH="/opt/PostgreSQL/10/bin:$PATH"
      before_install: true
      install: |
        docker build \
          --build-arg PGVERSION=${PGVERSION} \
          --build-arg PATH="${PATH}" \
          --build-arg RUBYVERSION="${TRAVIS_RUBY_VERSION}" \
          -t pg \
          -f Dockerfile-$DOCKER \
          .
      script: docker run -t pg
  # Test cross compilation only with 2.4
  exclude:
    - rvm: "2.2"
      env: "PGCROSS=true"
    - rvm: "2.5"
      env: "PGCROSS=true"
    - rvm: ruby-head
      env: "PGCROSS=true"
  allow_failures:
    - rvm: ruby-head
    - env:
        - DOCKER=i686
        - PGVERSION=10.0-1-linux
        - PATH="/opt/PostgreSQL/10/bin:$PATH"
  fast_finish: true
before_install:
  - gem install bundler
  - bundle install
  # Download and install postgresql version to test against in /opt (for non-cross compile only)
  - |
    if [ -z "$PGCROSS" ]; then
      wget http://get.enterprisedb.com/postgresql/postgresql-$PGVERSION.run && \
        chmod +x postgresql-$PGVERSION.run && \
        sudo ./postgresql-$PGVERSION.run --extract-only 1 --mode unattended
    fi
script: |
  if [ -z "$PGCROSS" ]; then
    rake compile test
  else
    rake gem:windows
  fi
